
shopify_api_key: fc06eb3741af3cf26125937082d3d2de
shopify_secret: 30b335fc4bc498deb428997159c3f472

# email credentials aren't required for dev if you're using Letter Opener
email_username: TODO from Sendgrid
email_password: TODO from Sendgrid

segment_write_key: TODO from Segment
